// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeBSOnRNbPDGFTJsSu9rQNBlc1Og2MNPY',
    appId: '1:893961780876:web:1d5ee9d56f150e032945a9',
    messagingSenderId: '893961780876',
    projectId: 'twilio-voip-app',
    authDomain: 'twilio-voip-app.firebaseapp.com',
    storageBucket: 'twilio-voip-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr8r3aq2O7BhiCZ3BDHgpnjMBTocOjdbo',
    appId: '1:893961780876:android:52959859dda9eb032945a9',
    messagingSenderId: '893961780876',
    projectId: 'twilio-voip-app',
    storageBucket: 'twilio-voip-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLG5ton-8MFRSj00JXvrgLjeaxdYiC1_o',
    appId: '1:893961780876:ios:426faf093cc5f54d2945a9',
    messagingSenderId: '893961780876',
    projectId: 'twilio-voip-app',
    storageBucket: 'twilio-voip-app.appspot.com',
    iosBundleId: 'com.twilio.twilioVoiceExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLG5ton-8MFRSj00JXvrgLjeaxdYiC1_o',
    appId: '1:893961780876:ios:426faf093cc5f54d2945a9',
    messagingSenderId: '893961780876',
    projectId: 'twilio-voip-app',
    storageBucket: 'twilio-voip-app.appspot.com',
    iosBundleId: 'com.twilio.twilioVoiceExample',
  );
}
